// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofxyumqneangphbdvzim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9meHl1bXFuZWFuZ3BoYmR2emltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjcxMzcsImV4cCI6MjA2MDU0MzEzN30.hhGWYtzMtr5MjjaG0vgcs2vDL3ZBWYV9R4RrNPt-Nio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);